services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5444:5432'
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=password123
      - PGADMIN_LISTEN_PORT=9098
    ports:
      - '9098:9098'
    depends_on:
      - postgres
    links:
      - postgres

  api:
    build: ./
    restart: unless-stopped
    environment:
      - POSTGRES_URL=postgres:5432
    ports:
        - 8080:8080
  front:
    build: ./src/main/frontend
    restart: unless-stopped
    ports:
        - 8081:80
    links:
      - api
volumes:
  postgres-data: